name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "My First Action!"
      - name: Print goodbye
        run: |
          echo "Goodbye!"
          echo "See you later!"
